services:
  - type: worker
    name: meu-bot
    env: python

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

    buildCommand: pip install -r requirements.txt
    startCommand: python bot_total_autonomo.py
